### PR TITLE
New timing code

### PR DESCRIPTION
**Pull request by joonazan**
#34

### CODE REVIEW

**Comment by xkortex** [comment]
Looks like you are running off of the develop branch. Can you either rebase or wait for the develop changes to land?

**Comment by MaxRobinsonTheGreat** [comment]
Agree with @xkortex you should rebase it from develop and set the pr to merge to master, there are updates to the code there.
How is performance with your changes?

**Comment by MaxRobinsonTheGreat** [comment]
Just checked it out, I'm seeing the same issue that I had on [my branch](https://github.com/MaxRobinsonTheGreat/LifeEngine/tree/interval-improvments), it seems to slow down much more significantly than the current version with setInterval. 

I don't currently have a super consistent benchmark for this, but on my machine it lags to ~15 fps with just a few hundred organisms, much worse than current version. Same problem on my branch.

**Comment by joonazan** [comment]
Ah, I accidentally committed the console.log.

I did not notice the same slowdown. It could be related to Chrome or different hardware, like for example if rendering is slower for you.

One thing that could improve overall performance would be putting the simulation in a web worker.

**Comment by lancelot2112** [comment]
I think it's in how it's scheduled.  
setInterval with a 10ms frame interval will work like the following (100fps)
code-runtime: [ 5ms ]-----[ 5ms ]-----[ 12ms ------- ][ 5ms ]
interrupt:         |                |                |                    | <-- will wait until previous exec is done then interrupt immediately, may catch 
                                                                                     back up if next frame is < 8ms

the way it looks like the setTimeout in the code is working will produce the following
code-runtime: [ 5ms ]---------[ 5ms ]-----[ 12ms ------- ]---------[ 5ms ]
interrupt:         |                     |               |                                 | 
setTimeout{10ms}:    |---------          |---------               |---------- 

Not going to improve exec through timer manipulation I think.  See more timing analysis in #68

**Comment by lancelot2112** [comment]
if you move the "setTimeout" code to the beginning of the updateSimulation() call it will replicate the "setInterval" behavior.

```javascript
updateSimulation() {
   setTimeout(func,1000/fps); //starts counting from start of exec instead of after simulation runs (less dead time)
   simulation.update();
}
```

**Pull request closed without merging**
