### PR TITLE
Fixed FPS calculation issue by moving to a higher performance timer a…

### PR DESCRIPTION
**Pull request by lancelot2112**
…nd isolating the simulation timer from the render timer.  Created a timer class to contain all timing logic.  Slowed down render to 30ms to allow for more simulation time.

### CODE REVIEW

**Comment by lancelot2112** [comment]
approving

**Comment by lancelot2112** [comment]
fixes #42

**Comment by MaxRobinsonTheGreat** [comment]
Hey this should be fixed with #45, its in the develop branch right now. 
If you think you can still improve it you can rebase and start with the updated code.

**Comment by lancelot2112** [comment]
I saw that afterwards :) I'm looking at it now.  Wrapping my head around git, come from a clearcase background

**Comment by xkortex** [comment]
@lancelot2112 https://youtu.be/1ffBJ4sVUb4 ;)

Best git guide on the net IMHO.

Rebase basically plucks your branch from the node it is on and applies it to the target commit node. If there are overlapping changes, you will get conflicts, just like merges. IDEs make this process a bit easier. There's also cherry-pick which is great if your branch is a single commit (and you can squash to make it a single commit).

**Comment by MaxRobinsonTheGreat** [comment]
Changes moved to #68

**Pull request closed without merging**
