### PR TITLE
Camo cell

### PR DESCRIPTION
**Pull request by adamorgler**
Added camo cell. When a camo cell is observed, all cells beyond the camo cell are hidden from the observer.

### CODE REVIEW

**Comment by MaxRobinsonTheGreat** [comment]
Closed for now until ideas are more solidified.

**Comment by MaxRobinsonTheGreat** [comment]
I have reopened this PR as a mod. I'm not intending to merge it in, but would like your work to be visible.

**Comment by MaxRobinsonTheGreat** [comment]
I am closing PRs I consider mods and moving them to the discord server

**Comment by adamorgler** [comment]
sounds good

**Pull request closed without merging**
